[project]
name = "pypomo"
version = "0.1.0"
description = "A CLI timer with named timers and compound durations"
readme = "README.md"
license = "MIT"
license-files = ["LICENSE"]
authors = [
    { name = "Andrew Davidson", email = "drace.davidson@gmail.com" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
pypomo = "pypomo:main"

[build-system]
requires = ["uv_build>=0.12.21,<0.13.0"]
build-backend = "uv_build"
